/** @brief Defines constants for configurable properties for the library
*
*  Typically these properties are set via
*  #Assimp::Importer::SetPropertyFloat,
*  #Assimp::Importer::SetPropertyInteger or
*  #Assimp::Importer::SetPropertyString,
*  depending on the data type of a property. All properties have a
*  default value. See the doc for the mentioned methods for more details.
*
*  The corresponding functions for use with the plain-c API are:
*  #aiSetImportPropertyInteger,
*  #aiSetImportPropertyFloat,
*  #aiSetImportPropertyString
*/
package assimp

CONFIG_GLOB_MEASURE_TIME :: "GLOB_MEASURE_TIME"

CONFIG_IMPORT_NO_SKELETON_MESHES :: "IMPORT_NO_SKELETON_MESHES"

CONFIG_PP_SBBC_MAX_BONES :: "PP_SBBC_MAX_BONES"

CONFIG_PP_CT_MAX_SMOOTHING_ANGLE :: "PP_CT_MAX_SMOOTHING_ANGLE"

CONFIG_PP_CT_TEXTURE_CHANNEL_INDEX :: "PP_CT_TEXTURE_CHANNEL_INDEX"

CONFIG_PP_GSN_MAX_SMOOTHING_ANGLE :: "PP_GSN_MAX_SMOOTHING_ANGLE"

CONFIG_IMPORT_MDL_COLORMAP :: "IMPORT_MDL_COLORMAP"

CONFIG_PP_RRM_EXCLUDE_LIST :: "PP_RRM_EXCLUDE_LIST"

CONFIG_PP_PTV_KEEP_HIERARCHY :: "PP_PTV_KEEP_HIERARCHY"

CONFIG_PP_PTV_NORMALIZE :: "PP_PTV_NORMALIZE"

CONFIG_PP_PTV_ADD_ROOT_TRANSFORMATION :: "PP_PTV_ADD_ROOT_TRANSFORMATION"

CONFIG_PP_PTV_ROOT_TRANSFORMATION :: "PP_PTV_ROOT_TRANSFORMATION"

CONFIG_CHECK_IDENTITY_MATRIX_EPSILON :: "CHECK_IDENTITY_MATRIX_EPSILON"

CONFIG_PP_FD_REMOVE :: "PP_FD_REMOVE"

CONFIG_PP_FD_CHECKAREA :: "PP_FD_CHECKAREA"

CONFIG_PP_OG_EXCLUDE_LIST :: "PP_OG_EXCLUDE_LIST"

CONFIG_PP_SLM_TRIANGLE_LIMIT :: "PP_SLM_TRIANGLE_LIMIT"

CONFIG_PP_SLM_VERTEX_LIMIT :: "PP_SLM_VERTEX_LIMIT"

CONFIG_PP_LBW_MAX_WEIGHTS :: "PP_LBW_MAX_WEIGHTS"

CONFIG_PP_DB_THRESHOLD :: "PP_DB_THRESHOLD"

CONFIG_PP_DB_ALL_OR_NONE :: "PP_DB_ALL_OR_NONE"

CONFIG_PP_ICL_PTCACHE_SIZE :: "PP_ICL_PTCACHE_SIZE"

CONFIG_PP_RVC_FLAGS :: "PP_RVC_FLAGS"

CONFIG_PP_SBP_REMOVE :: "PP_SBP_REMOVE"

CONFIG_PP_FID_ANIM_ACCURACY :: "PP_FID_ANIM_ACCURACY"

CONFIG_PP_FID_IGNORE_TEXTURECOORDS :: "PP_FID_IGNORE_TEXTURECOORDS"

CONFIG_PP_TUV_EVALUATE :: "PP_TUV_EVALUATE"

CONFIG_FAVOUR_SPEED :: "FAVOUR_SPEED"

CONFIG_IMPORT_SCHEMA_DOCUMENT_PROVIDER :: "IMPORT_SCHEMA_DOCUMENT_PROVIDER"

CONFIG_IMPORT_FBX_READ_ALL_GEOMETRY_LAYERS :: "IMPORT_FBX_READ_ALL_GEOMETRY_LAYERS"

CONFIG_IMPORT_FBX_READ_ALL_MATERIALS :: "IMPORT_FBX_READ_ALL_MATERIALS"

CONFIG_IMPORT_FBX_READ_MATERIALS :: "IMPORT_FBX_READ_MATERIALS"

CONFIG_IMPORT_FBX_READ_TEXTURES :: "IMPORT_FBX_READ_TEXTURES"

CONFIG_IMPORT_FBX_READ_CAMERAS :: "IMPORT_FBX_READ_CAMERAS"

CONFIG_IMPORT_FBX_READ_LIGHTS :: "IMPORT_FBX_READ_LIGHTS"

CONFIG_IMPORT_FBX_READ_ANIMATIONS :: "IMPORT_FBX_READ_ANIMATIONS"

CONFIG_IMPORT_FBX_READ_WEIGHTS :: "IMPORT_FBX_READ_WEIGHTS"

CONFIG_IMPORT_FBX_STRICT_MODE :: "IMPORT_FBX_STRICT_MODE"

CONFIG_IMPORT_FBX_PRESERVE_PIVOTS :: "IMPORT_FBX_PRESERVE_PIVOTS"

CONFIG_IMPORT_FBX_OPTIMIZE_EMPTY_ANIMATION_CURVES :: "IMPORT_FBX_OPTIMIZE_EMPTY_ANIMATION_CURVES"

CONFIG_IMPORT_FBX_EMBEDDED_TEXTURES_LEGACY_NAMING :: "AI_CONFIG_IMPORT_FBX_EMBEDDED_TEXTURES_LEGACY_NAMING"

CONFIG_IMPORT_REMOVE_EMPTY_BONES :: "AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES"

CONFIG_FBX_CONVERT_TO_M :: "AI_CONFIG_FBX_CONVERT_TO_M"

CONFIG_IMPORT_FBX_IGNORE_UP_DIRECTION :: "AI_CONFIG_IMPORT_FBX_IGNORE_UP_DIRECTION"

CONFIG_FBX_USE_SKELETON_BONE_CONTAINER :: "AI_CONFIG_FBX_USE_SKELETON_BONE_CONTAINER"

CONFIG_IMPORT_GLOBAL_KEYFRAME :: "IMPORT_GLOBAL_KEYFRAME"

CONFIG_IMPORT_MD3_KEYFRAME :: "IMPORT_MD3_KEYFRAME"
CONFIG_IMPORT_MD2_KEYFRAME :: "IMPORT_MD2_KEYFRAME"
CONFIG_IMPORT_MDL_KEYFRAME :: "IMPORT_MDL_KEYFRAME"
CONFIG_IMPORT_MDC_KEYFRAME :: "IMPORT_MDC_KEYFRAME"
CONFIG_IMPORT_SMD_KEYFRAME :: "IMPORT_SMD_KEYFRAME"
CONFIG_IMPORT_UNREAL_KEYFRAME :: "IMPORT_UNREAL_KEYFRAME"

CONFIG_IMPORT_MDL_HL1_READ_ANIMATIONS :: "IMPORT_MDL_HL1_READ_ANIMATIONS"

CONFIG_IMPORT_MDL_HL1_READ_ANIMATION_EVENTS :: "IMPORT_MDL_HL1_READ_ANIMATION_EVENTS"

CONFIG_IMPORT_MDL_HL1_TRANSFORM_COORD_SYSTEM :: "TRANSFORM COORDSYSTEM FOR HS! MODELS"

CONFIG_IMPORT_MDL_HL1_READ_BLEND_CONTROLLERS :: "IMPORT_MDL_HL1_READ_BLEND_CONTROLLERS"

CONFIG_IMPORT_MDL_HL1_READ_SEQUENCE_TRANSITIONS :: "IMPORT_MDL_HL1_READ_SEQUENCE_TRANSITIONS"

CONFIG_IMPORT_MDL_HL1_READ_ATTACHMENTS :: "IMPORT_MDL_HL1_READ_ATTACHMENTS"

CONFIG_IMPORT_MDL_HL1_READ_BONE_CONTROLLERS :: "IMPORT_MDL_HL1_READ_BONE_CONTROLLERS"

CONFIG_IMPORT_MDL_HL1_READ_HITBOXES :: "IMPORT_MDL_HL1_READ_HITBOXES"

CONFIG_IMPORT_MDL_HL1_READ_MISC_GLOBAL_INFO :: "IMPORT_MDL_HL1_READ_MISC_GLOBAL_INFO"

CONFIG_IMPORT_SMD_LOAD_ANIMATION_LIST :: "IMPORT_SMD_LOAD_ANIMATION_LIST"

CONFIG_IMPORT_AC_SEPARATE_BFCULL :: "IMPORT_AC_SEPARATE_BFCULL"

CONFIG_IMPORT_AC_EVAL_SUBDIVISION :: "IMPORT_AC_EVAL_SUBDIVISION"

CONFIG_IMPORT_UNREAL_HANDLE_FLAGS :: "UNREAL_HANDLE_FLAGS"

CONFIG_IMPORT_TER_MAKE_UVS :: "IMPORT_TER_MAKE_UVS"

CONFIG_IMPORT_ASE_RECONSTRUCT_NORMALS :: "IMPORT_ASE_RECONSTRUCT_NORMALS"

CONFIG_IMPORT_MD3_HANDLE_MULTIPART :: "IMPORT_MD3_HANDLE_MULTIPART"

CONFIG_IMPORT_MD3_SKIN_NAME :: "IMPORT_MD3_SKIN_NAME"

CONFIG_IMPORT_MD3_LOAD_SHADERS :: "IMPORT_MD3_LOAD_SHADERS"

CONFIG_IMPORT_MD3_SHADER_SRC :: "IMPORT_MD3_SHADER_SRC"

CONFIG_IMPORT_LWO_ONE_LAYER_ONLY :: "IMPORT_LWO_ONE_LAYER_ONLY"

CONFIG_IMPORT_MD5_NO_ANIM_AUTOLOAD :: "IMPORT_MD5_NO_ANIM_AUTOLOAD"

CONFIG_IMPORT_LWS_ANIM_START :: "IMPORT_LWS_ANIM_START"

CONFIG_IMPORT_LWS_ANIM_END :: "IMPORT_LWS_ANIM_END"

CONFIG_IMPORT_IRR_ANIM_FPS :: "IMPORT_IRR_ANIM_FPS"

CONFIG_IMPORT_OGRE_MATERIAL_FILE :: "IMPORT_OGRE_MATERIAL_FILE"

CONFIG_IMPORT_OGRE_TEXTURETYPE_FROM_FILENAME :: "IMPORT_OGRE_TEXTURETYPE_FROM_FILENAME"

CONFIG_ANDROID_JNI_ASSIMP_MANAGER_SUPPORT :: "AI_CONFIG_ANDROID_JNI_ASSIMP_MANAGER_SUPPORT"

CONFIG_IMPORT_IFC_SKIP_SPACE_REPRESENTATIONS :: "IMPORT_IFC_SKIP_SPACE_REPRESENTATIONS"

CONFIG_IMPORT_IFC_CUSTOM_TRIANGULATION :: "IMPORT_IFC_CUSTOM_TRIANGULATION"

CONFIG_IMPORT_IFC_SMOOTHING_ANGLE :: "IMPORT_IFC_SMOOTHING_ANGLE"

CONFIG_IMPORT_IFC_CYLINDRICAL_TESSELLATION :: "IMPORT_IFC_CYLINDRICAL_TESSELLATION"

CONFIG_IMPORT_COLLADA_IGNORE_UP_DIRECTION :: "IMPORT_COLLADA_IGNORE_UP_DIRECTION"

CONFIG_IMPORT_COLLADA_IGNORE_UNIT_SIZE :: "IMPORT_COLLADA_IGNORE_UNIT_SIZE"

CONFIG_IMPORT_COLLADA_USE_COLLADA_NAMES :: "IMPORT_COLLADA_USE_COLLADA_NAMES"

CONFIG_EXPORT_XFILE_64BIT :: "EXPORT_XFILE_64BIT"

CONFIG_EXPORT_POINT_CLOUDS :: "EXPORT_POINT_CLOUDS"

CONFIG_USE_GLTF_PBR_SPECULAR_GLOSSINESS :: "USE_GLTF_PBR_SPECULAR_GLOSSINESS"

CONFIG_EXPORT_GLTF_UNLIMITED_SKINNING_BONES_PER_VERTEX :: "USE_UNLIMITED_BONES_PER VERTEX"

CONFIG_EXPORT_FBX_TRANSPARENCY_FACTOR_REFER_TO_OPACITY :: "EXPORT_FBX_TRANSPARENCY_FACTOR_REFER_TO_OPACITY"

CONFIG_EXPORT_BLOB_NAME :: "EXPORT_BLOB_NAME"

CONFIG_GLOBAL_SCALE_FACTOR_KEY :: "GLOBAL_SCALE_FACTOR"

CONFIG_APP_SCALE_KEY :: "APP_SCALE_FACTOR"
